export const DIAG_SECCIONES = [
  {
    num: 1,
    label: 'Motor',
    titulo: 'Compartimiento Motor',
    items: [
      'Aceite de motor: nivel y condición',
      'Refrigerante: nivel y condición',
      'Líquido de frenos',
      'Líquido de dirección hidráulica (si aplica)',
      'Aceite de transmisión (si aplica / verificable)',
      'Líquido limpiaparabrisas',
      'Filtro de aire',
      'Filtro de polen',
      'Filtro de aceite / condición visible',
      'Correas auxiliares',
      'Mangueras y conexiones visibles',
      'Fugas visibles de motor o refrigeración',
      'Soportes de motor visibles',
      'Estado general del motor',
    ],
  },
  {
    num: 2,
    label: 'Frenos',
    titulo: 'Sistema de Frenos',
    items: [
      'Pastillas delanteras',
      'Pastillas traseras',
      'Discos delanteros',
      'Discos traseros',
      'Flexibles / líneas visibles',
      'Fugas del sistema',
      'Freno de estacionamiento',
    ],
  },
  {
    num: 3,
    label: 'Susp. Del.',
    titulo: 'Dirección y Suspensión Delantera',
    items: [
      'Cremallera de dirección',
      'Terminales / axiales',
      'Bandejas / bujes / rótulas',
      'Bieletas / barra estabilizadora',
      'Amortiguadores delanteros',
      'Espirales / cazoletas / guardapolvos',
      'Homocinéticas / fuelles',
      'Observación general tren delantero',
    ],
  },
  {
    num: 4,
    label: 'Susp. Tras.',
    titulo: 'Suspensión Trasera',
    items: [
      'Bujes / brazos / bandejas traseras',
      'Amortiguadores traseros',
      'Espirales / soportes / guardapolvos',
      'Bieletas / barra estabilizadora si aplica',
      'Rodamientos / holguras visibles si aplica',
      'Observación general tren trasero',
    ],
  },
  {
    num: 5,
    label: 'Bajos',
    titulo: 'Transmisión y Bajos',
    items: [
      'Fugas de transmisión',
      'Fugas de diferencial / transfer si aplica',
      'Estado inferior de motor y caja',
      'Semiejes / palieres si aplica',
      'Escape y soportes',
      'Observación general de bajos',
    ],
  },
  {
    num: 6,
    label: 'Ruedas',
    titulo: 'Neumáticos y Ruedas',
    items: [
      'Neumáticos delanteros',
      'Neumáticos traseros',
      'Desgaste irregular',
      'Presión / condición general',
      'Repuesto si aplica',
      'Comentario general de neumáticos',
    ],
  },
  {
    num: 7,
    label: 'Escaneo',
    titulo: 'Escaneo y Funcionamiento',
    items: [
      'Testigos / escaneo si aplica',
      'Códigos relevantes',
      'Estado básico de batería / carga si aplica',
      'Observación general de funcionamiento',
    ],
  },
  {
    num: 8,
    label: 'Ruta',
    titulo: 'Prueba de Ruta',
    sinFotos: true,
    items: [
      'Motor',
      'Transmisión',
      'Frenos',
      'Dirección / alineación',
      'Ruidos de suspensión',
      'Vibraciones',
      'Temperatura de operación',
      'Comentario prueba de ruta',
    ],
  },
  {
    num: 9,
    label: 'Final',
    titulo: 'Diagnóstico Final',
    items: [
      'Hallazgos principales',
      'Trabajos recomendados',
      'Prioridad: urgente / recomendable / preventivo',
      'Comentario final del técnico',
    ],
  },
]

export function getDiagSeccion(num) {
  return DIAG_SECCIONES.find((s) => s.num === num)
}
